# Generated by Django 4.2.5 on 2024-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_ID', models.CharField(max_length=10)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Domain', models.CharField(max_length=25)),
                ('Job_Description', models.CharField(max_length=255)),
                ('Min_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Max_Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Job_Type', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=25)),
                ('Eligibility_Criteria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Email_Address', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
    ]
